### PR TITLE
Merge recent changes from dev and VSCode installation into main

### PR DESCRIPTION
**Pull request by ateucher**
This takes the work that @betolink had done in the `dev` branch (which is currently the image used in the hub) and recent work merged into main from #32, #33, etc

### CODE REVIEW

**Comment by ateucher** [comment]
@betolink this mostly looks good except that in VSCode can't find the main Jupyter kernel (Running BYOI with `openscapes/python:693163b`), only opendap.

It is there:
```
(notebook) jovyan@jupyter-ateucher:~$ jupyter kernelspec list
Available kernels:
  opendap    /srv/conda/envs/notebook/share/jupyter/kernels/opendap
  python3    /srv/conda/envs/notebook/share/jupyter/kernels/python3
```

but VSCode doesn't see it

image.

I'm trying to track down why, but if you have any tips I'm happy to hear them!

**Comment by ateucher** [comment]
Also - VSCode seems to be behaving better now, the notebook environment seems to be default, and opendap is an option:

image


The extensions are installed and working as they should

**Comment by betolink** [comment]
Sorry for the super delayed time to check this, I'm merging it and I think we can address the VSCode integration as a separate issue. @ateucher  I think we should include the same con-lock on actions that CryoCloud has so we don't have to do it ourselves. And another thing we might want to take a look at is how can we use something like dependabot to update our packages and open PRs, I haven't looked in a while if there is a way to integrate it with Conda environments.

**Comment by ateucher** [comment]
Thanks @betolink. I think the vscode integration is now not bad, though some real-world user testing will tell us for sure. 

> same con-lock on actions that CryoCloud has so we don't have to do it ourselves.

I like that idea!

**Pull request merged**
